### ISSUE TITLE
can u get me a .bin for vu9p keccak-tribus?

### ISSUE THREAD

**Issue by nursie999** [digitalcruncher/keccak-tribus#1]
can u get me a .bin for vu9p keccak-tribus?
email chickman9662@gmail.com

**Comment by digitalcruncher** [comment]
You don't need a .bin file.
Use .bit files from https://github.com/digitalcruncher/keccak-tribus instead.

**Comment by nursie999** [comment]
Error at line 39, file ./sysfs_io.c (2) [No such file or directory]
how to do it?
